ui:
	pyrcc5 {{cookiecutter.package_name}}/ui_designer/resources.qrc -o {{cookiecutter.package_name}}/ui_designer/resources_rc.py
	pyuic5 {{cookiecutter.package_name}}/ui_designer/mainwindow.ui -o {{cookiecutter.package_name}}/ui_designer/mainwindow_qt.py")
